### ISSUE TITLE
Warning: Received `false` for a non-boolean attribute `completed`.

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#996]
Getting this on the team selection page:

```
react_devtools_backend.js:4026 Warning: Received `false` for a non-boolean attribute `completed`.

If you want to write it to the DOM, pass a string instead: completed="false" or completed={value.toString()}.

If you used to conditionally omit it with completed={condition && value}, pass completed={condition ? value : undefined} instead.
    at span
    at Tooltip (http://localhost:3000/static/js/bundle.js:202677:28)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at ApeInfoTooltip (http://localhost:3000/static/js/bundle.js:2503:3)
    at div
    at Paper (http://localhost:3000/static/js/bundle.js:197746:23)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at Stepper (http://localhost:3000/static/js/bundle.js:201436:33)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at div
    at AllocationPage (http://localhost:3000/static/js/bundle.js:29561:19)
    at Routes (http://localhost:3000/static/js/bundle.js:403420:5)
    at LoggedInRoutes
    at AppRoutes (http://localhost:3000/static/js/bundle.js:40772:84)
    at main
    at Styled.div
    at Suspense
    at div
    at Styled.div
    at MainLayout (http://localhost:3000/static/js/bundle.js:6582:25)
    at Router (http://localhost:3000/static/js/bundle.js:403353:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:402284:5)
    at Web3ReactProvider (http://localhost:3000/static/js/bundle.js:248714:27)
    at MuiPickersUtilsProvider (http://localhost:3000/static/js/bundle.js:213194:20)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:213455:24)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:399676:21)
    at InnerErrorBoundary (http://localhost:3000/static/js/bundle.js:4075:5)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:4195:3)
    at SnackbarProvider (http://localhost:3000/static/js/bundle.js:349831:24)
    at RecoilRoot_INTERNAL (http://localhost:3000/static/js/bundle.js:416049:3)
    at RecoilRoot (http://localhost:3000/static/js/bundle.js:416205:5)
    at App
```

**Comment by CryptoGraffe** [comment]
related:

```
react_devtools_backend.js:4026 Warning: Received `true` for a non-boolean attribute `last`.

If you want to write it to the DOM, pass a string instead: last="true" or last={value.toString()}.
    at span
    at Tooltip (http://localhost:3000/static/js/bundle.js:202677:28)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at ApeInfoTooltip (http://localhost:3000/static/js/bundle.js:2503:3)
    at div
    at Paper (http://localhost:3000/static/js/bundle.js:197746:23)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at Stepper (http://localhost:3000/static/js/bundle.js:201436:33)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at div
    at AllocationPage (http://localhost:3000/static/js/bundle.js:29561:19)
    at Routes (http://localhost:3000/static/js/bundle.js:403420:5)
    at LoggedInRoutes
    at AppRoutes (http://localhost:3000/static/js/bundle.js:40772:84)
    at main
    at Styled.div
    at Suspense
    at div
    at Styled.div
    at MainLayout (http://localhost:3000/static/js/bundle.js:6582:25)
    at Router (http://localhost:3000/static/js/bundle.js:403353:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:402284:5)
    at Web3ReactProvider (http://localhost:3000/static/js/bundle.js:248714:27)
    at MuiPickersUtilsProvider (http://localhost:3000/static/js/bundle.js:213194:20)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:213455:24)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:399676:21)
    at InnerErrorBoundary (http://localhost:3000/static/js/bundle.js:4075:5)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:4195:3)
    at SnackbarProvider (http://localhost:3000/static/js/bundle.js:349831:24)
    at RecoilRoot_INTERNAL (http://localhost:3000/static/js/bundle.js:416049:3)
    at RecoilRoot (http://localhost:3000/static/js/bundle.js:416205:5)
    at App
```

**Comment by karelianpie** [comment]
Unable to reproduce this one, still an issue @CryptoGraffe?
