### ISSUE TITLE
Warning: React does not recognize the `alternativeLabel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `alternativelabel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by CryptoGraffe** [coordinape/coordinape#997]
Getting this on the team selection page

```
react_devtools_backend.js:4026 Warning: React does not recognize the `alternativeLabel` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `alternativelabel` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at span
    at Tooltip (http://localhost:3000/static/js/bundle.js:202677:28)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at ApeInfoTooltip (http://localhost:3000/static/js/bundle.js:2503:3)
    at div
    at Paper (http://localhost:3000/static/js/bundle.js:197746:23)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at Stepper (http://localhost:3000/static/js/bundle.js:201436:33)
    at WithStyles (http://localhost:3000/static/js/bundle.js:214488:31)
    at div
    at AllocationPage (http://localhost:3000/static/js/bundle.js:29561:19)
    at Routes (http://localhost:3000/static/js/bundle.js:403420:5)
    at LoggedInRoutes
    at AppRoutes (http://localhost:3000/static/js/bundle.js:40772:84)
    at main
    at Styled.div
    at Suspense
    at div
    at Styled.div
    at MainLayout (http://localhost:3000/static/js/bundle.js:6582:25)
    at Router (http://localhost:3000/static/js/bundle.js:403353:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:402284:5)
    at Web3ReactProvider (http://localhost:3000/static/js/bundle.js:248714:27)
    at MuiPickersUtilsProvider (http://localhost:3000/static/js/bundle.js:213194:20)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:213455:24)
    at QueryClientProvider (http://localhost:3000/static/js/bundle.js:399676:21)
    at InnerErrorBoundary (http://localhost:3000/static/js/bundle.js:4075:5)
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:4195:3)
    at SnackbarProvider (http://localhost:3000/static/js/bundle.js:349831:24)
    at RecoilRoot_INTERNAL (http://localhost:3000/static/js/bundle.js:416049:3)
    at RecoilRoot (http://localhost:3000/static/js/bundle.js:416205:5)
    at App
```

**Comment by karelianpie** [comment]
I'm unable to reproduce this one, does it still happen to you @CryptoGraffe?
